### ISSUE TITLE
Gnome 42: Icon hover effect persists

### ISSUE THREAD

**Issue by danstewart** [home-sweet-gnome/dash-to-panel#1620]
**Things to do first**
- [x] Confirm that the problem persists when Dash-to-Panel is the only enabled extension. To do so, disable every other extension, then restart gnome-shell by running the `r` command from the prompt that appears when pressing Alt+F2 on an X.org session, or by logging out/in on a Wayland session.
- [x] Look for Dash-to-Panel errors in your log. To do so, run the `journalctl /usr/bin/gnome-shell -f -o cat &` command and reproduce the problem.
- [x] Search existing opened and closed issues to see if the problem has already been reported.

**Describe the bug**
The hover effect on the dock icons remains active when hovering out of dock, but deactivates when hovering off of an icon within the dock.

See video below.

**Linux distribution and version**
Fedora 36 beta

**GNOME Shell version**
GNOME Shell 42.0

**Dash-to-Panel version**
46

**Where was Dash-to-Panel installed from?**
The GNOME extensions website

**Screenshots / Video captures**

https://user-images.githubusercontent.com/10670565/162698908-55656e0b-9225-4d59-b8bb-3686f33816ad.mp4

**Comment by charlesg99** [comment]
See #1619: That's a Mutter bug. On my Arch system it was fixed by updating to 42.0-2 last thursday. Here is some more info about it https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2321

**Comment by danstewart** [comment]
Thanks :+1: Sorry I missed #1619

**Comment by charlesg99** [comment]
No problem, I knew this issue would pop a few times :wink:. I'll leave it pinned for now until everybody gets the new mutter version.

**Comment by Uldreth** [comment]
On Fedora 36 `mutter --version` gives 42.0, but the source package is called `mutter-42.0-3.fc36.src.rpm`, so I assume I am on mutter 42.0-3. The issue however still persists.

**Comment by charlesg99** [comment]
Not sure how it's packaged on Fedora. [On Arch](https://github.com/archlinux/svntogit-packages/blob/packages/mutter/trunk/PKGBUILD) it is mutter 42.0, but they cherry picked the [2 commits](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2321/commits) that fixed the issue. Maybe Fedora only packages based on repo tags, in which case you'd have to wait for 42.1.

**Comment by charlesg99** [comment]
Fedora added the fix: https://bodhi.fedoraproject.org/updates/FEDORA-2022-e822ccefac

**Comment by danstewart** [comment]
Got the mutter update today and can confirm everything is working fine on Fedora 36 :slightly_smiling_face:
