### ISSUE TITLE
Clicking on app icon using touch does not bring app to foreground

### ISSUE THREAD

**Issue by T99Rots** [home-sweet-gnome/dash-to-panel#1676]
**Describe the bug**
I have a laptop with a touchscreen and i've noticed that by clicking on app icons using touch, a app will open if it wasn't opened yet, but when the app is already opened, clicking on the app icon does not bring the app to the foreground, i've dug through the code a bit and added some print statements and i noticed the TaskbarAppIcon.activate function gets called with button 0 while it should be getting called with button 1, this causes the buttonAction to stay 0 which in turn means nothings happens when you click the app icon, i've locally fixed it by changing the else if statement to also accept button 0 next to button 1 but as the button should not be 0 i'm hesitant to make a pull request as this seems like a hacky solution, also i've tried to figure out why this function is getting called with button 0 but since i'm unfamiliar with the gjs ecosystem i'm not quite sure how to do a stack trace similar to console.trace() on web so this is as far as i got. 

**Linux distribution and version**
I'm on Ubuntu 22.04 

**GNOME Shell version**
GNOME Shell 42.0

**Dash-to-Panel version**
I'm on Dash to Panel version 50

**Where was Dash-to-Panel installed from?**
Dash to panel was installed from https://extensions.gnome.org/

**Comment by justjosias** [comment]
I'm experiencing the same problem on Fedora 36 with GNOME 42 and Dash to Panel 50.

**Comment by zazou99vlc** [comment]
Same problem , Fedora 36 . touchpanel does not do the same thing as a mouse click. Asus T102HA. I have to use the activities button to switch applications.
![imagen](https://user-images.githubusercontent.com/109170401/178556226-40d2c298-8f1c-48c1-b19d-e57f659667d8.png)

**Comment by pub001** [comment]
Same here, Manjaro 21.3.5 with GNOME 42.3 and Dash to Panel 50.
@T99Rots would you kindly share more information about the "hacky" solution?:)
I don't find this TaskbarAppIcon.activate function.. Thank you!

**Comment by catscratchedme** [comment]
Same problem here. Also, the "show desktop" button in the bottom right of the panel also doesn't respond to touch

**Comment by T99Rots** [comment]
@pub001 i've added a pull request, you should be able to pull the code from there and install that to fix the issue

**Comment by T99Rots** [comment]
@catscratchedme i've updated the pull request to also fix your issue

**Comment by pub001** [comment]
> @pub001 i've added a pull request, you should be able to pull the code from there and install that to fix the issue

Hero. That's what you are!:) Thank you!

**Comment by roman083** [comment]
same here, 

- minimize and maximize with touch won't work, but with stylus or mouse it will
- "show Desktop" button also no reaction

Fedora 37 and Manjaro with Gnome 43 and Dash to Panel 52 using a Lenovo Yoga x380

**Comment by matt1432** [comment]
This issue is still here and after merging the up to date repo with T99Rots's commits, building the app and trying it, the problem is fixed.

**Comment by dustojnikhummer** [comment]
> This issue is still here, but after merging the up to date repo with T99Rots's commits, building the app and trying it, the problem is fixed.

I'm too stupid to compile it myself, any idea if it will be pushed to prod for everyone? Or at least a precompiled package I can install?

**Comment by matt1432** [comment]
> > This issue is still here, but after merging the up to date repo with T99Rots's commits, building the app and trying it, the problem is fixed.
> 
> I'm too stupid to compile it myself, any idea if it will be pushed to prod for everyone? Or at least a precompiled package I can install?

You can simply clone my [fork](https://github.com/matt1432/dash-to-panel-touch-fix), go into the cloned directory and run ```make install```

You then just need to logout and log back in to see it working if it is enabled.

You can see for yourself that my fork is literally just T99Rots' commits and a few I merged from the main repository to update it.

I tried to reach out to get the pull request merged but I have no news. Hopefully they will soon.

**Comment by charlesg99** [comment]
I'll do a PR run over the weekend and probably merge this one. I don't have a tactile screen to test with, but I'll take your word for it!

**Comment by dustojnikhummer** [comment]
> > > This issue is still here, but after merging the up to date repo with T99Rots's commits, building the app and trying it, the problem is fixed.
> > 
> > 
> > I'm too stupid to compile it myself, any idea if it will be pushed to prod for everyone? Or at least a precompiled package I can install?
> 
> You can simply clone my [fork](https://github.com/matt1432/dash-to-panel-touch-fix), go into the cloned directory and run `make install`
> 
> You then just need to logout and log back in to see it working if it is enabled.
> 
> You can see for yourself that my fork is literally just T99Rots' commits and a few I merged from the main repository to update it.
> 
> I tried to reach out to get the pull request merged but I have no news. Hopefully they will soon.

I git cloned that link, ran sudo make install

Sadly the taskbar doesn't work properly. Dash to Panel reports version 9999. Are there any logs I can provide?

**Comment by matt1432** [comment]
> I git cloned that link, ran sudo make install
> 
> Sadly the taskbar doesn't work properly. Dash to Panel reports version 9999. Are there any logs I can provide?

That's weird, I'm not an expert at all so I don't know about logs, but I'm pretty the version 9999 thing also happens to me and doesn't affect anything.

For the fact that it doesn't work properly, I don't know what to tell you. I guess I didn't run the command with sudo so that might make a difference:
```
$ git clone https://github.com/matt1432/dash-to-panel-touch-fix.git
$ cd dash-to-panel-touch-fix/
$ make install
```

**Comment by JamesFrederik** [comment]
It works great on my Thinkpad T495 touchscreen running Fedora 36.

I installed by downloading a zip and then copy pasting the JS files into the existing extension directory.

**Comment by dustojnikhummer** [comment]
> > I git cloned that link, ran sudo make install
> > Sadly the taskbar doesn't work properly. Dash to Panel reports version 9999. Are there any logs I can provide?
> 
> That's weird, I'm not an expert at all so I don't know about logs, but I'm pretty the version 9999 thing also happens to me and doesn't affect anything.
> 
> For the fact that it doesn't work properly, I don't know what to tell you. I guess I didn't run the command with sudo so that might make a difference:
> 
> ```
> $ git clone https://github.com/matt1432/dash-to-panel-touch-fix.git
> $ cd dash-to-panel-touch-fix/
> $ make install
> ```

Now it works! Version still reports as 9999 but I can reopen a minimized app. Still can't minimize by tapping open app on the taskbar, but that might be intended behavior. Much appreciated!

**Comment by matt1432** [comment]
> > > I git cloned that link, ran sudo make install
> > > Sadly the taskbar doesn't work properly. Dash to Panel reports version 9999. Are there any logs I can provide?
> > 
> > 
> > That's weird, I'm not an expert at all so I don't know about logs, but I'm pretty the version 9999 thing also happens to me and doesn't affect anything.
> > For the fact that it doesn't work properly, I don't know what to tell you. I guess I didn't run the command with sudo so that might make a difference:
> > ```
> > $ git clone https://github.com/matt1432/dash-to-panel-touch-fix.git
> > $ cd dash-to-panel-touch-fix/
> > $ make install
> > ```
> 
> Now it works! Version still reports as 9999 but I can reopen a minimized app. Still can't minimize by tapping open app on the taskbar, but that might be intended behavior. Much appreciated!

You're welcome! There is a setting to change that behavior in the extensions setting so that might be a way to fix your problem.

**Comment by cetu86** [comment]
I'm no longer using gnome (switched to kde/plasma). But it's sad to see that this just gets closed without even knowing whether the fix got merged or not.

**Comment by tomsik-radek** [comment]
> I'm no longer using gnome (switched to kde/plasma). But it's sad to see that this just gets closed without even knowing whether the fix got merged or not. For me the fix worked. For me it has real use case: Even if i'm not using the notebook screen as a touch screen it was nice to use the bottom of the screen for task switching. That's the part of the screen I can easily reach with my fingers while typing. Kind of use it like a second row of F-keys.

It's not closed, it got marked as inactive due to inactivity.

**Comment by T99Rots** [comment]
> I'm no longer using gnome (switched to kde/plasma). But it's sad to see that this just gets closed without even knowing whether the fix got merged or not. For me the fix worked. For me it has real use case: Even if i'm not using the notebook screen as a touch screen it was nice to use the bottom of the screen for task switching. That's the part of the screen I can easily reach with my fingers while typing. Kind of use it like a second row of F-keys.

Even more sad is that I made a PR that fixes the issue which I use locally and it's never even been looked at

**Comment by tomsik-radek** [comment]
> > I'm no longer using gnome (switched to kde/plasma). But it's sad to see that this just gets closed without even knowing whether the fix got merged or not. For me the fix worked. For me it has real use case: Even if i'm not using the notebook screen as a touch screen it was nice to use the bottom of the screen for task switching. That's the part of the screen I can easily reach with my fingers while typing. Kind of use it like a second row of F-keys.
> 
> Even more sad is that I made a PR that fixes the issue which I use locally and it's never even been looked at

Work taught me that in tickets sometimes both sides need to remind the other side.

**Comment by matt1432** [comment]
I tried to remind them and I even made my own fork to make it up to date with master, so there would not be any conflicts but nothing has been done

**Comment by Thorsten42** [comment]
I am also facing this issue. A fork of current master with @T99Rots pull request is fixing this issue. Would be really nice to have this merged here :/

**Comment by Thorsten42** [comment]
Hi, I am now using v62 and at least for me this issue is now fixed. Thanks a lot!
