### ISSUE TITLE
Gray background at every taskbar icon

### ISSUE THREAD

**Issue by AlcatrAAz** [home-sweet-gnome/dash-to-panel#2118]
Hello all,

I have a strange problem that every Icon in my task bar has an additional half transparent background. So I have the "normal" background when hover or a program is focused and then an additional background for the  icons. This problem is only at the program icons and maybe the "show apps". Time and Power, Ethernet sound is okay.

I already tried changing the values in the stylesheet.css of dash-to-panel. Additional I added sections from the stylesheet.css from /usr/share/.. that sounded plausible and changed the backgroundcolors.

How can I remove these icon backgrounds?

![dash2panel_gray_background](https://github.com/home-sweet-gnome/dash-to-panel/assets/53754707/0645f0c2-2787-47b5-bfd8-c0750ec4211d)

Ubuntu 24.04 fresh installation. Gnome 46

Thanks in advance!

**Comment by youarentdoneyet** [comment]
Same thing
![Screenshot from 2024-06-01 19-24-48](https://github.com/home-sweet-gnome/dash-to-panel/assets/3647961/e8cdf4bf-b509-43c2-b2bd-2ecb9fde8a3c)

**Comment by AlcatrAAz** [comment]
Sorry seems duplicated and fixed in master. I edit the stylesheet.css to get the fix.

Commit: https://github.com/home-sweet-gnome/dash-to-panel/commit/632d3bdcfcb3a49439aed6b0544bb93259d86777

One question: What is the CSS code to change the background color of the focused application? I can find hover and clicked but not the CSS part for the application that is focused.

**Comment by barathbheeman** [comment]
@AlcatrAAz how exactly did you fix it? can you pls post step-by-step? I have the same issue.

**Comment by AlcatrAAz** [comment]
Sure!

Open file explorer (Nautilus)
Press Control + h to show hidden files
Go to something like this: ~/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/
Open stylesheet.css in Text editor
Add the following line like here https://github.com/home-sweet-gnome/dash-to-panel/commit/632d3bdcfcb3a49439aed6b0544bb93259d86777
Save file
Log out or restart

If someone has the the answer for this, would be really appreciated.
"What is the CSS code to change the background color of the focused application? I can find hover and clicked but not the CSS part for the application that is focused."

**Comment by SebastJava** [comment]
> One question: What is the CSS code to change the background color of the focused application? I can find hover and clicked but not the CSS part for the application that is focused.

@AlcatrAAz 

I don't know about the CSS, but you could change it easily, just using the nice GUI:

Dash to Panel Settings > Style tab > Running indicator style (Focused app) > click on the cog icon (⚙) > Highlight focused application: on > Highlight opacity: your value (0-100)... (see screenshots below)

![bitmap](https://github.com/user-attachments/assets/ae98cf76-164d-425d-bc73-89bfecf50f95)

![bitmap](https://github.com/user-attachments/assets/9817bc09-61a6-44b6-8133-ba7705da173b)

**Comment by SebastJava** [comment]
Still having an issue with the ShowsApps in the bottom-left corner. This little background square on hover. I still get that after applying the https://github.com/home-sweet-gnome/dash-to-panel/commit/632d3bdcfcb3a49439aed6b0544bb93259d86777 fix. That's just a very small annoyance. A small trace remaining, after eliminating the bug...

![ShowApps-hover](https://github.com/user-attachments/assets/b9bab936-07db-4a73-9906-f53dca588437)

**Comment by gcrabbe** [comment]
@SebastJava Does c3f885d38833dca364d9ab8bb3110125f2e1295e fix it?

**Comment by SebastJava** [comment]
@gcrabbe Yes! Thanks. (logout-login required after applying this fix...)
