### ISSUE TITLE
Dash to Panel is loading before ArcMenu on Manual install ?

### ISSUE THREAD

**Issue by One-EyedDog** [home-sweet-gnome/dash-to-panel#2248]
I'm on gnome 48.beta using ubuntu plucky and have installed dash to panel from the main branch.

the ArcMenu from extension-manager auto download shows the arc menu button correctely on dash to panel, but the menu panel don't show when clicking (error with gobject), after that a removed the ArcMenu extension from extension manager and installed manualy form its main source.

Now when i log in the ArcMenu button don't appear in dash to panel but the menu appear when a press (Left Super window button), 

When i disable and enable Dash to panel, the ArcMenu button loads correctely in the panel and function normaly when clicking 

https://i.postimg.cc/zf6JmFnm/Captura-de-tela-de-2025-02-27-06-31-51.png

[https://i.postimg.cc/zf6JmFnm/Captura-de-tela-de-2025-02-27-06-31-51.png](url)

It looks like Dash to Panel is loading before ArcMenu?

**Comment by charlesg99** [comment]
Not too sure, normally even if ArcMenu loads after dash to panel, it should properly go into the panel. I can't reproduce the issue on Gnome 48.beta with ArcMenu's master branch even if it was installed after dash to panel. Does it happen if you enable both extensions, then log out/in? Do you see errors at the end of your log `journalctl /usr/bin/gnome-shell`?

![Image](https://github.com/user-attachments/assets/0999e1cf-5a05-4ac7-b2e7-7c5da2a29b44)

**Comment by One-EyedDog** [comment]
if you can't reproduce this, then probably i already broke my system, i will try with another clean installation, if  is working with you installation the problem is in my side, i already missup and recovered this system many times, sorry for disturbance and good work.

curious if i execute disable and enable dash to panel with arcmenu enabled the button appers normally, then a log out and in and he will hide again

fev 27 16:29:54 nemo-pc gnome-shell[2672]: Obtained a high priority EGL context
fev 27 16:29:55 nemo-pc gnome-shell[2672]: Using public X11 display :1024, (using :1025 for managed services)
fev 27 16:29:55 nemo-pc gnome-shell[2672]: Using Wayland display name 'wayland-0'
fev 27 16:29:56 nemo-pc gnome-shell[2672]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
fev 27 16:29:56 nemo-pc gnome-shell[2672]: Will monitor session c1
fev 27 16:29:56 nemo-pc gnome-shell[2672]: Extension tiling-assistant@ubuntu.com already installed in /usr/share/gnome-shell/extensions/tiling-assistant@ubuntu.com. /usr/share/gnome-shell/e>
fev 27 16:29:56 nemo-pc gnome-shell[2672]: Extension ubuntu-dock@ubuntu.com already installed in /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com. /usr/share/gnome-shell/extensions/>
fev 27 16:29:56 nemo-pc gnome-shell[2672]: Extension ubuntu-appindicators@ubuntu.com already installed in /usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com. /usr/share/gnome>
fev 27 16:29:56 nemo-pc gnome-shell[2672]: Extension ding@rastersoft.com already installed in /usr/share/gnome-shell/extensions/ding@rastersoft.com. /usr/share/gnome-shell/extensions/ding@r>
fev 27 16:29:56 nemo-pc gnome-shell[2672]: Failed to parse saved session file: Falha ao abrir arquivo “/var/lib/gdm3/.config/mutter/sessions/105975e0fe4875a193174068459375583000000026480000>
fev 27 16:29:56 nemo-pc gnome-shell[2672]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
fev 27 16:29:57 nemo-pc gnome-shell[2672]: Registering session with GDM
fev 27 16:30:02 nemo-pc gnome-shell[3392]: Running GNOME Shell (using mutter 48.beta) as a Wayland display server
fev 27 16:30:02 nemo-pc gnome-shell[3392]: Thread 'KMS thread' will be using high priority scheduling
fev 27 16:30:02 nemo-pc gnome-shell[3392]: Device '/dev/dri/card1' prefers shadow buffer
fev 27 16:30:02 nemo-pc gnome-shell[3392]: Added device '/dev/dri/card1' (amdgpu) using atomic mode setting.
fev 27 16:30:02 nemo-pc gnome-shell[3392]: Created gbm renderer for '/dev/dri/card1'
fev 27 16:30:02 nemo-pc gnome-shell[3392]: Boot VGA GPU /dev/dri/card1 selected as primary
fev 27 16:30:02 nemo-pc gnome-shell[3392]: Obtained a high priority EGL context
fev 27 16:30:03 nemo-pc gnome-shell[3392]: Using public X11 display :0, (using :1 for managed services)
fev 27 16:30:03 nemo-pc gnome-shell[3392]: Using Wayland display name 'wayland-0'
fev 27 16:30:03 nemo-pc gnome-shell[3392]: Unset XDG_SESSION_ID, getCurrentSessionProxy() called outside a user session. Asking logind directly.
fev 27 16:30:03 nemo-pc gnome-shell[3392]: Will monitor session 3
fev 27 16:30:03 nemo-pc gnome-shell[3392]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
fev 27 16:30:09 nemo-pc gnome-shell[3392]: GNOME Shell started at Thu Feb 27 2025 16:30:03 GMT-0300 (Horário Padrão de Brasília)
fev 27 16:30:09 nemo-pc gnome-shell[3392]: Registering session with GDM
fev 27 16:30:10 nemo-pc gnome-shell[2672]: Connection to xwayland lost
fev 27 16:30:10 nemo-pc gnome-shell[2672]: Xwayland terminated, exiting since it was mandatory
fev 27 16:30:10 nemo-pc gnome-shell[2672]: JS ERROR: Gio.IOErrorEnum: Xwayland exited unexpectedly
                                           @resource:///org/gnome/shell/ui/init.js:21:20
fev 27 16:30:10 nemo-pc gnome-shell[2672]: Execution of main.js threw exception: Module resource:///org/gnome/shell/ui/init.js threw an exception
fev 27 16:30:10 nemo-pc gnome-shell[3392]: Launching DING process
fev 27 16:30:10 nemo-pc gnome-shell[3392]: DING: Detected async api for thumbnails
fev 27 16:30:10 nemo-pc gnome-shell[3392]: DING: (gjs:4065): Gjs-WARNING **: 16:30:10.542: GLib.unix_signal_add has been moved to a separate platform-specific library. Please update your co>
fev 27 16:30:10 nemo-pc gnome-shell[3392]: DING: 0 DesktopManager() ["/usr/share/gnome-shell/extensions/ding@rastersoft.com/app/desktopManager.js":265:13]
fev 27 16:30:10 nemo-pc gnome-shell[3392]: DING: 1 anonymous() ["/usr/share/gnome-shell/extensions/ding@rastersoft.com/app/ding.js":180:26]
fev 27 16:30:10 nemo-pc gnome-shell[3392]: DING: 2 anonymous() ["/usr/share/gnome-shell/extensions/ding@rastersoft.com/app/ding.js":197:21]
fev 27 16:30:10 nemo-pc gnome-shell[3392]: DING: 3 <TOP LEVEL> ["/usr/share/gnome-shell/extensions/ding@rastersoft.com/app/ding.js":206:13]
fev 27 16:30:10 nemo-pc gnome-shell[3392]: DING: ** Message: 16:30:10.601: Connecting to org.freedesktop.Tracker3.Miner.Files
fev 27 16:30:10 nemo-pc gnome-shell[3392]: DING: DBus interface for Switcheroo control (net.hadess.SwitcherooControl) is now available.
fev 27 16:30:10 nemo-pc gnome-shell[3392]: DING: DBus interface for Gvfs daemon (org.gtk.vfs.Metadata) is now available.
fev 27 16:30:10 nemo-pc gnome-shell[3392]: DING: DBus interface for File-roller (org.gnome.ArchiveManager1) is now available.
fev 27 16:30:10 nemo-pc gnome-shell[3392]: Received notification for window. 0 notifications remaining.
fev 27 16:30:10 nemo-pc gnome-shell[3392]: DING: DBus interface for Nautilus (org.gnome.Nautilus.FileOperations2) is now available.
fev 27 16:30:10 nemo-pc gnome-shell[3392]: DING: DBus interface for Nautilus (org.freedesktop.FileManager1) is now available.
fev 27 16:30:10 nemo-pc gnome-shell[3392]: DING: GNOME nautilus 48.beta

**Comment by IanWorley** [comment]
@charlesg99 This is the issue I am experience right now it just so happen this bug decide to happen just when donation feature decided to roll out.

**Comment by GSF1200S** [comment]
The exact same thing happens to me with the extension that was pushed today. I suspect this has to do with the donation feature that was added. In terms of how it's implemented, it took over (as in concealed) ArcMenu placing a heart icon in its place; after selecting the switch in dash-to-panel options to dismiss the heart icon, now every time I log into Gnome, ArcMenu (and Vitals) is not visible. As is the case with the originator of this issue, pressing Meta still reveals ArcMenu. Vitals (which I have in the center box) is also not visible upon login, and the Activities button which is placed in between the center and right box (I set as "Stack to left" to place it right against the right side of Vitals) is all the way to the left up against the task bar. It's as if the center and left boxes don't load. 

I have to open dash-to-panel settings, make un-visible the left box (immediately Vitals shows in center box), then make the left box visible again and ArcMenu will show. From this point on, the panel works normally (as in how it did before the breaking update)... until I logout or reboot (where it will happen again the next time I login to Gnome).

This is 100% repeatable. I run Fedora 41 Workstation. I have 2 27" 1440P monitors (no scaling).

**Comment by R8bert** [comment]
same probem here

**Comment by AndrewZaech** [comment]
I think this issue is caused by https://github.com/home-sweet-gnome/dash-to-panel/blob/master/src/panel.js#L537

When Dash to Panel is first enabled, a panel box may initially be empty, which sets its visibility to false.

If ArcMenu or other extensions that use addToStatusArea() are enabled after dash to panel, the visibility of the panel boxes aren't updated.

**Comment by charlesg99** [comment]
Thanks Andrew, that makes sense! Guess I'll release another maintenance release later today 😂

**Comment by charlesg99** [comment]
I saw a video of someone playing with the positioning options of dash to panel and he demonstrated that it is confusing if a box has no child and visible, the elements around it don't react to the stacking options because of that empty box. Anyway, I reverted this and it should be fixed on the master branch, thanks again!

**Comment by GSF1200S** [comment]
The latest update (68) completely fixes the loading issue for both the left box and the center box for me. I'm reluctant to close this myself in case others still have an issue. Thanks

**Comment by One-EyedDog** [comment]
Hello @charlesg99, @GSF1200S  and all, i can confirm, two of my system updated automatically to version 68 without donation button and now the arc menu button is visible and acting normally, thank guys

Ubuntu Plucky Puffin (development branch)
Gnome 48
Wayland
6.12.0-16-generic
