### ISSUE TITLE
In Ubuntu 19.04, using Firefox 67.0, the shortkey to hide/revel panel is not working. (Gnome 3.32.1)

### ISSUE THREAD

**Issue by PranavBhattarai** [home-sweet-gnome/dash-to-panel#622]
It is not responding. But it used to. 
But in Chrome and other application, it is working.
Even moving the cursor to the panel doesn't reveal the panel.

Note: This doesn't happen on a regular basis.

**Comment by charlesg99** [comment]
Hello, I can't reproduce that on Ubuntu 19.04, xorg or wayland, using dash to panel v19 or master. Not sure what you mean by "using firefox", but I tested with maximized firefox 66.0.3 windows, fullscreen, in/out focus, etc. and the panel always correctly appears using the hotkey of the mouse. Please disable every other extensions, restart gnome-shell and try again. Thanks!

**Comment by PranavBhattrai** [comment]
Yes, it is working for now.

**Comment by charlesg99** [comment]
Not sure why this was reopened... The following hasn't changed on my end:

> I can't reproduce that on Ubuntu 19.04, xorg or wayland, using dash to panel v19 or master. Not sure what you mean by "using firefox", but I tested with maximized firefox 66.0.3 windows, fullscreen, in/out focus, etc. and the panel always correctly appears using the hotkey of the mouse. Please disable every other extensions, restart gnome-shell and try again. 

Thanks!

**Comment by eyagulee** [comment]
@charlesg99 I have the same(maybe similar) issue in Gnome 3.32.2 (Fedora 30). The panel is set to be at the top of the screen. Can you try the following methods to reproduce it ?

1. Watch youtube video in fullscreen mode in Firefox(67.0.4) or
2. Open a file in fullscreen mode in Evince pdf reader

Then use the mouse pointer  or the shortcut (<kbd>Super + i</kbd> for me) to auto-reveal the panel.
After using the shortcut, the panel is revealed but is not displayed. I can click on the icons(wifi, battery etc.) which opens the gnome shell menu.

**Comment by charlesg99** [comment]
Hello eyagulee, while trying to reproduce the issue, I encountered a bug that happens when enabling intellihide while a fullscreen app is displayed. When that happened, intellihide wouldn't work correctly, so this might be related. This should now be fixed on master if you want to give it a try. Thanks!

**Comment by eyagulee** [comment]
The problem still exists in the master branch. To be precise, this only happens in Xorg.

> After using the shortcut, the panel is revealed but is not displayed. I can click on the icons(wifi, battery etc.) which opens the gnome shell menu.

What I meant is that after the glitch happens in Firefox , leave the fullscreen view and open some another program(say Nautilus). Then use the **shortcut** to reveal the panel if it's hidden. Go back to Firefox and the panel will be invisible(but is in revealed state). You won't be able to click on "maximize, minimize or close" buttons of Firefox window because they are under the panel.
