### ISSUE TITLE
Dash to panel does not show previews when reducing applications

### ISSUE THREAD

**Issue by brofjst** [home-sweet-gnome/dash-to-panel#743]
OS: Arch Linux
gnome-shell 1:3.34.0+152+g0fdbde910-1
When i reduce to icon an application, the preview shows a black window until i expand another one.
![Screenshot from 2019-09-25 15-52-07](https://user-images.githubusercontent.com/33980971/65607808-6ba7b500-dfad-11e9-86d0-fb179fe0c5ee.png)

**Comment by charlesg99** [comment]
Hello, I can't reproduce this so far (tried the latest master on 3.34, xorg and wayland ). What version of the extension are you using? Is this only for firefox? Could it be related to #605? Thanks!

**Comment by dykow** [comment]
![Screenshot from 2019-09-25 22-12-26](https://user-images.githubusercontent.com/16824096/65636612-22b62780-dfd2-11e9-86aa-3473dc29ecd3.png)
The same issue:
Fedora 31
Gnome 3.34
DTP 23

It happens when not hovering over for some time (can't specify how long and if always), hovering over app icon on panel (activating preview) a few times fixes it for a while. Application independent.

**Comment by charlesg99** [comment]
It should be fixed on the latest master (since 981ffc17612696046fb5cba95d2ae97d0868f60d),  could you guys please give it a try and confirm that it solves the issue? Thanks!

**Comment by dykow** [comment]
Master version seems to be ok, at least so far.

**Comment by dykow** [comment]
Still same problem on master

**Comment by brofjst** [comment]
I've tried the master but the issue persists.
The issue is not related only to firefox: [image](https://i.imgur.com/3Go2dr7.png)
I'm on Xorg

**Comment by dykow** [comment]
I noticed, that sometimes no hovering effect is visible at all, even "backlighting" of an icon.

**Comment by charlesg99** [comment]
Thanks for the feedback! Weird, I couldn't reproduce the issue in a 3.34 Rawhide VM, but yesterday night I updated my Arch to 3.34 and then I saw the same as you. Looks like another Clutter bug stemming from the 3.34 optimization... Not sure If I waited long enough before updating, seems pretty unstable (the worst is that when I restart gnome shell, most of my programs are closed grrr!).

I pushed another workaround for this issue on master, could you please pull/install again and see if that helps?

**Comment by dykow** [comment]
Seems to be OK, so far.

**Comment by brofjst** [comment]
With the last update the problem is solved, thank you!
